name: Deploy MLflow and Flask app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start containers with docker-compose
        run: |
          cd mlflow
          docker compose up -d --build

      - name: Timeout
        run: sleep 20

      - name: Test Flask app and MLflow
        run: |
          curl --fail http://localhost:5000 || exit 1
          curl --fail http://localhost:5500 || exit 1
